# Generated by Django 3.2.8 on 2021-12-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elo_rating',
            name='rating_before',
            field=models.IntegerField(default=1000),
        ),
    ]
