# Generated by Django 3.2.8 on 2021-12-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmatch',
            name='next_matches',
            field=models.ManyToManyField(related_name='_clubs_groupmatch_next_matches_+', to='clubs.GroupMatch'),
        ),
    ]
