# Generated by Django 3.2.8 on 2021-12-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='capacity',
            field=models.SmallIntegerField(choices=[(2, 'Two'), (4, 'Four'), (8, 'Eight'), (16, 'Sixteen'), (24, 'Twenty_four'), (32, 'Thirty_Two'), (48, 'Forty_Eight'), (64, 'Sixty_Four')]),
        ),
    ]
