# Generated by Django 3.2.8 on 2021-12-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='number_of_contenders',
        ),
    ]
