# Generated by Django 3.2.8 on 2021-12-09 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='contender',
            field=models.ManyToManyField(related_name='_clubs_tournaments_contender_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournaments',
            name='number_of_contenders',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(models.SmallIntegerField(choices=[(2, 'Two'), (4, 'Four'), (8, 'Eight'), (16, 'Sixteen'), (32, 'Thirty_Two'), (64, 'Sixty_Four')]))]),
        ),
    ]
