# Generated by Django 3.2.5 on 2021-11-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='ClubOwner',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Officer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'Banned'), (1, 'Applicant'), (2, 'Member'), (3, 'Officer'), (4, 'Owner')], default=1),
        ),
    ]
