# Generated by Django 3.2.8 on 2021-12-13 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='current_stage',
            field=models.CharField(choices=[('F', 'Finished'), ('E', 'Elimination rounds'), ('G32', 'Group stage'), ('S', 'Start')], default='S', max_length=3),
        ),
        migrations.CreateModel(
            name='GroupPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_group_points', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.group')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_points', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('player2_points', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.group')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.match')),
                ('next_matches', models.ManyToManyField(null=True, related_name='_clubs_groupmatch_next_matches_+', to='clubs.Match')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.tournament'),
        ),
    ]
