# Generated by Django 3.2.8 on 2021-12-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_groupmatch_next_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmatch',
            name='next_matches',
        ),
        migrations.CreateModel(
            name='GroupMatchNextMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.groupmatch')),
                ('next_matches', models.ManyToManyField(related_name='_clubs_groupmatchnextmatches_next_matches_+', to='clubs.GroupMatch')),
            ],
        ),
    ]
