# Generated by Django 3.2.8 on 2021-12-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_elo_rating_rating_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elo_rating',
            name='rating_before',
            field=models.IntegerField(),
        ),
    ]
