# Generated by Django 3.2.9 on 2021-11-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20211119_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('OFFICER', 'Officer'), ('MEMBER', 'Member')], default='MEMBER', max_length=50, verbose_name='Type'),
        ),
    ]
