# Generated by Django 3.2.8 on 2021-12-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20211212_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current_stage',
            field=models.CharField(choices=[('F', 'Finished'), ('E', 'Elimination rounds')], default='E', max_length=2),
        ),
    ]
