# Generated by Django 3.2.8 on 2021-12-10 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_remove_tournaments_number_of_contenders'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='elo_rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
