# Generated by Django 3.2.8 on 2021-12-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_tournaments_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='full',
        ),
    ]
