# Generated by Django 3.2.8 on 2021-12-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211210_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='elo_rating',
            field=models.SmallIntegerField(default=1000),
        ),
    ]
