# Generated by Django 3.2.8 on 2021-12-03 12:56

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211130_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
