# Generated by Django 3.2.8 on 2021-12-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20211212_1155'),
        ('clubs', '0003_remove_tournaments_full'),
    ]

    operations = [
    ]
