# Generated by Django 3.2.8 on 2021-12-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_role_elo_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='elo_rating',
        ),
    ]
