# Generated by Django 3.2.9 on 2021-11-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20211119_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CLUBOWNER', 'ClubOwner'), ('OFFICER', 'Officer'), ('MEMBER', 'Member')], default='MEMBER', max_length=50, verbose_name='Type'),
        ),
    ]
