# Generated by Django 3.2.8 on 2021-12-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20211214_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmatch',
            name='player1_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='groupmatch',
            name='player2_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True),
        ),
    ]
