# Generated by Django 3.2.8 on 2021-12-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20211214_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmatch',
            name='player1_points',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='groupmatch',
            name='player2_points',
            field=models.FloatField(default=0, null=True),
        ),
    ]
