# Generated by Django 3.2.9 on 2021-11-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_statement',
            field=models.CharField(default='personal statement', max_length=600),
        ),
    ]
