# Generated by Django 3.2.8 on 2021-12-10 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_role_elo_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(0, 'No_club'), (1, 'Applicant'), (2, 'Member'), (3, 'Officer'), (4, 'Owner')], default=1)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='club',
            name='users',
            field=models.ManyToManyField(through='clubs.UserInClub', to=settings.AUTH_USER_MODEL),
        ),
    ]
