# Generated by Django 3.2.8 on 2021-12-06 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20211206_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='organiser',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
