# Generated by Django 3.2.5 on 2021-11-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20211121_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clubs.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CLUBOWNER', 'ClubOwner'), ('OFFICER', 'Officer'), ('MEMBER', 'Member'), ('APPLICANT', 'Applicant')], default='APPLICANT', max_length=50, verbose_name='Type'),
        ),
    ]
