# Generated by Django 3.2.8 on 2021-12-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='elo_rating',
            field=models.IntegerField(default=1000),
        ),
    ]
