# Generated by Django 3.2.8 on 2021-12-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20211210_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinclub',
            name='elo_rating',
            field=models.IntegerField(default=1000),
        ),
    ]
