# Generated by Django 3.2.8 on 2021-11-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20211121_1428'),
        ('clubs', '0008_alter_user_username'),
    ]

    operations = [
    ]
