# Generated by Django 3.2.8 on 2021-12-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_auto_20211214_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppoints',
            name='total_group_points',
            field=models.FloatField(default=0),
        ),
    ]
