# Generated by Django 3.2.8 on 2021-12-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_grouppoints_total_group_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmatch',
            name='player1_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='groupmatch',
            name='player2_points',
            field=models.FloatField(default=0),
        ),
    ]
