# Generated by Django 3.2.8 on 2021-12-06 17:50

import clubs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_tournaments_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='organiser',
            field=models.ForeignKey(limit_choices_to={clubs.models.Role: 3}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
