# Generated by Django 3.2.8 on 2021-12-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_match_matchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='capacity',
            field=models.SmallIntegerField(choices=[(2, 'Two'), (4, 'Four'), (8, 'Eight'), (16, 'Sixteen'), (32, 'Thirty_Two'), (64, 'Sixty_Four')]),
        ),
    ]
